
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Im Ausland | Bobby's Travel Log
subtitle: "Some documentation of Bobby's abroad trip!"
# Base URL of site. It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "/im-ausland" # the subpath of your site
url: "https://bobbylcraig.com/im-ausland/" # the base hostname & protocol for your site
# cover: "/assets/cover.png"
# logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"
